FROM lscr.io/linuxserver/obsidian:latest

# Instala dependências de desenvolvimento do sistema
RUN apt-get update && apt-get install -y \
    curl \
    git \
    nodejs \
    ripgrep \
    && rm -rf /var/lib/apt/lists/*
RUN npm install -g opencode-ai

# Garante permissão de execução global para o binário do OpenCode
RUN chmod +x /usr/local/bin/opencode || true

EXPOSE 3000